#! /usr/bin/env python
# -*- coding:utf-8 -*-
#
# This file is a part of TPCI_SEDRA project
# Copyright (c) INRIA 2015
#
# Contributor (s) : Gaetan Harter
# Contacts : gaetan.harter@inria.fr
# 
# This project is headed by SED Rhone-Alpes service at INRIA.
#

from abc_and_sphere import sphere
sphere.main()
